### ISSUE TITLE
error: can not read property 'big_head' of undefined

### ISSUE THREAD

**Issue by windmemory** [lijiarui/wechaty-puppet-padchat#113]
```shell
02:01:11 ERR Config ###########################
02:01:11 ERR Config unhandledRejection: TypeError: Cannot read property 'big_head' of undefined [object Promise]
02:01:11 ERR Config ###########################
02:01:11 ERR Config ###########################
02:01:11 ERR Config unhandledRejection: TypeError: Cannot read property 'big_head' of undefined [object Promise]
02:01:11 ERR Config ###########################
02:01:11 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'big_head' of undefined)
Config TypeError: Cannot read property 'big_head' of undefined
    at PuppetPadchat.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/puppet-padchat.ts:1000:30)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:21:12)
    at PuppetPadchat.roomMemberRawPayloadParser (/bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:750:16)
    at PuppetPadchat.<anonymous> (/wechaty/node_modules/wechaty-puppet/src/puppet.ts:1073:35)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/wechaty-puppet/dist/src/puppet.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
02:01:11 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'big_head' of undefined)
Config TypeError: Cannot read property 'big_head' of undefined
    at PuppetPadchat.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/puppet-padchat.ts:1000:30)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:21:12)
    at PuppetPadchat.roomMemberRawPayloadParser (/bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:750:16)
    at PuppetPadchat.<anonymous> (/wechaty/node_modules/wechaty-puppet/src/puppet.ts:1073:35)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/wechaty-puppet/dist/src/puppet.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kis87988** [comment]
```log
08:50:04 SILL PuppetPadchat roomMemberRawPayloadParser(undefined)
08:50:04 ERR Bot room.add() exception: TypeError: Cannot read property 'big_head' of undefined
    at PuppetPadchat.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/puppet-padchat.ts:1080:30)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:21:12)
    at PuppetPadchat.roomMemberRawPayloadParser (/bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:822:16)
    at PuppetPadchat.<anonymous> (/wechaty/node_modules/wechaty-puppet/src/puppet.ts:1114:35)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/wechaty-puppet/dist/src/puppet.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
[//]: # (Refer to 20180809)

**Comment by lijiarui** [comment]
ping @windmemory

**Comment by windmemory** [comment]
This needs more investigation.
