### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by AlphaFase** [lijiarui/wechaty-puppet-padchat#114]
```
⠹ [43/44] Installing node-expat@^2.3.15
WARN node unsupported "node@v6.14.2" is incompatible with xml2json@0.11.2 › joi@^13.1.2, expected node@>=8.9.0
⠸ [43/44] Installing topo@3.x.x
WARN node unsupported "node@v6.14.2" is incompatible with xml2json@0.11.2 › joi@13.4.0 › hoek@5.x.x, expected node@>=8.9.0
⠼ [43/44] Installing nan@^2.3.5
WARN node unsupported "node@v6.14.2" is incompatible with xml2json@0.11.2 › joi@13.4.0 › topo@3.x.x, expected node@>=8.0.0
⠸ [43/44] Installing punycode@2.x.xmake: Entering directory `/home/node/node_modules/_node-expat@2.3.16@node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
⠼ [43/44] Installing punycode@2.x.x../deps/libexpat/lib/xmlparse.c: In function ‘gather_time_entropy’:
../deps/libexpat/lib/xmlparse.c:780:7: warning: variable ‘gettimeofday_res’ set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^
⠦ [43/44] Installing punycode@2.x.x  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
⠧ [43/44] Installing punycode@2.x.x  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
⠙ [43/44] Installing punycode@2.x.x  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
make: g++: Command not found
make: *** [Release/obj.target/node_expat/node-expat.o] Error 127
make: Leaving directory `/home/node/node_modules/_node-expat@2.3.16@node-expat/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-862.3.3.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/node_modules/_node-expat@2.3.16@node-expat
gyp ERR! node -v v6.14.2
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
✖ Install fail! Error: Run "sh -c node-gyp rebuild" error, exit code 1
Error: Run "sh -c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

```

**Comment by lijiarui** [comment]
You node version should over 10, but log shows your node version is 6.14.2

**Comment by AlphaFase** [comment]
```
C:\Users\Administrator\Desktop\wechaty-puppet-padchat-master>node start
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\Desktop\wechaty-puppet-padchat
-master\start'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

```

安装好了，又到这个问题

**Comment by lijiarui** [comment]
> 1. 该用cnpm的地方，全写成npm
cnpm 是淘宝源，这是因为GFW 的原因，国内npm下载依赖的速度慢，才会使用cnpm。官方标准做法应该用npm，你不应该说因为你在墙内，你的terminal 不能翻墙，就说应该用cnpm

也可以给你个建议，购买国外的服务器，比如[digitalocean](https://m.do.co/c/6f830efbb356) 的Singapore服务器。

> 2. 配置文件里，没写要安装typescript， 没写要安装ts-node
是的，如果是ts 文件需要安装，如果想看js 的代码，建议你使用 [wechaty-getting-started](https://github.com/chatie/wechaty-getting-started) 的代码，通过配置环境变量 `WECHATY_PUPPET= padchat ` 来运行js 文件。

你这个意见很好，我们会在这个repo里面引入 [wechaty-getting-started](https://github.com/chatie/wechaty-getting-started) 作为教学, 也建议你去wechaty-getting-started 项目下学习。可以帮你节约时间

> 3. 代码真的可以运行吗
代码可以运行，因为我们公司提供基于这个API的Saas产品，并服务很多大企业客户了。

> 4. 我把主机给你，你帮我配置算了
你的windows电脑肯定是无法给我配置的。未来我们会推出云服务，底层配置都配好的。现阶段如果你仍然有问题，在你将问题说明白的前提下，我们愿意帮助你在你的服务器上配置并找到bug.
