### ISSUE TITLE
No userId when login to wechaty

### ISSUE THREAD

**Issue by windmemory** [lijiarui/wechaty-puppet-padchat#121]
```shell
14:00:35 WARN PadchatRpc WXQRCodeLogin, redirect 301
14:00:35 SILL PadchatRpc rpcCall(WXQRCodeLogin, ["wxid_df4nv3uo11u321","extdevnewpwd_CiNDS1FTWkhlZTRzNWZVVkFSMzh5UHlDejVAcXJ0aWNrZXRfMBJAZkU2OG5KckE0RnJ3QmhHNktMWFBJa3pFLW9lV01WQkVra0p2bjFrSW5aSVhYS21uTEZSdzNld3VZNnNMNDlQYhoYZ1NjY0Jnc2h5TmZwSWdOdkp4QThiZk1E"])
14:00:35 SILL PadchatRpc WXQRCodeLogin, login successfully!
14:00:35 VERB PuppetPadchatManager login()
14:00:35 VERB PuppetPadchatManager stopCheckScan()
14:00:35 VERB PuppetPadchatManager refresh62Data(, undefined)
14:00:35 SILL PadchatRpc rpcCall(WXHeartBeat, [])
14:00:36 SILL PadchatRpc WXHeartBeat result: {"status":0,"message":"ok"}
14:00:36 SILL PuppetPadchatManager refresh62Data() memorySlot is empty, init & return it
14:00:36 SILL PadchatRpc rpcCall(WXGenerateWxDat, [])
14:00:36 SILL PadchatRpc WXGenerateWxDat result: {"data":"YnBsaXN0MDDUAQIDBAUGCQpYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKIHCFUkbnVsbF8QIDUyZWIxNDU3ZjM4NTIwODY5ZTFhMTBhZjkzNDJjNmMzXxAPTlNLZXllZEFyY2hpdmVy0QsMVHJvb3SAAQgRGiMtMjc6QGN1eH0AAAAAAAABAQAAAAAAAAANAAAAAAAAAAAAAAAAAAAAfw==","message":"","status":0}
14:00:36 SILL PadchatRpc rpcCall(WXGetLoginToken, [])
14:00:36 SILL PadchatRpc WXGetLoginToken result: {"message":"","status":0,"token":"xFsdCEWLeqwypVCZJcP3NwF3RQcDXjXlfg1+CwfZoCLI+ZiBg3n0hmLFG6aPJ5fEANlond0knmh3i4qfF9QmvFHdZ/CQ76NvgcNnBxtD4+F/O3sFGBKN1Z9RMvFOl9bOpEA1xDuJ67zdOoLmBYBPcVU/h2TBnJvh8IxEQB1xQBWYPqQ1tOz8eP/W/DdRd2dY","uin":0}
14:00:36 VERB MemoryCard <Puppet#0<PuppetPadchat>()/PuppetPadchat#0> set(WECHATY_PUPPET_PADCHAT, [object Object])
14:00:36 VERB MemoryCard <Puppet#0<PuppetPadchat>()/PuppetPadchat#0> save() file: /bot/5b5a9105da24c27fa8f3125e.memory-card.json
14:00:36 VERB MemoryCard <> save() file: /bot/5b5a9105da24c27fa8f3125e.memory-card.json
14:00:36 VERB PuppetPadchatManager initCache(5b5a9105da24c27fa8f3125e, )
14:00:36 VERB PuppetPadchatManager initCache() inited 0 Contacts, 0 RoomMembers, 0 Rooms, cachedir="/bot/.wechaty/puppet-padchat-cache/5b5a9105da24c27fa8f3125e/"
14:00:36 SILL PuppetPadchatManager contactRawPayload()
14:00:36 SILL PuppetPadchatManager contactRawPayload() retry() attempt=1
14:00:36 ERR Config ###########################
14:00:36 ERR Config unhandledRejection: WriteError: key cannot be an empty String [object Promise]
14:00:36 ERR Config ###########################
14:00:36 ERR Config ###########################
14:00:36 ERR Config unhandledRejection: WriteError: key cannot be an empty String [object Promise]
14:00:36 ERR Config ###########################
14:00:36 ERR Config ###########################
14:00:36 ERR Config unhandledRejection: Error: should use WXGetRoomPayload because get a room id : [object Promise]
14:00:36 ERR Config ###########################
14:00:36 ERR Config ###########################
14:00:36 ERR Config unhandledRejection: Error: should use WXGetRoomPayload because get a room id : [object Promise]
14:00:36 ERR Config ###########################
14:00:36 ERR Config process.on(unhandledRejection) promise.catch(key cannot be an empty String)
Config WriteError: key cannot be an empty String
    at /bot/node_modules/flash-store/node_modules/levelup/lib/levelup.js:212:23
    at DB.AbstractLevelDOWN.del (/bot/node_modules/abstract-leveldown/abstract-leveldown.js:132:12)
    at LevelUP.del (/bot/node_modules/flash-store/node_modules/levelup/lib/levelup.js:210:11)
    at FlashStore$1.<anonymous> (/bot/node_modules/flash-store/bundles/flash-store.umd.js:250:63)
    at step (/bot/node_modules/flash-store/dist/config.js:11:19)
    at Object.next (/bot/node_modules/flash-store/bundles/flash-store.umd.js:4:53)
    at /bot/node_modules/flash-store/bundles/flash-store.umd.js:80:75
    at new Promise (<anonymous>)
    at __awaiter$1 (/bot/node_modules/flash-store/dist/flash-store.js:43:14)
    at FlashStore$1.delete (/bot/node_modules/flash-store/bundles/flash-store.umd.js:245:20)
    at FlashStoreSync.delete (/bot/node_modules/flash-store/bundles/flash-store.umd.js:850:53)
    at PadchatManager.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:295:41)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
14:00:36 ERR Config process.on(unhandledRejection) promise.catch(key cannot be an empty String)
Config WriteError: key cannot be an empty String
    at /bot/node_modules/flash-store/node_modules/levelup/lib/levelup.js:212:23
    at DB.AbstractLevelDOWN.del (/bot/node_modules/abstract-leveldown/abstract-leveldown.js:132:12)
    at LevelUP.del (/bot/node_modules/flash-store/node_modules/levelup/lib/levelup.js:210:11)
    at FlashStore$1.<anonymous> (/bot/node_modules/flash-store/bundles/flash-store.umd.js:250:63)
    at step (/bot/node_modules/flash-store/dist/config.js:11:19)
    at Object.next (/bot/node_modules/flash-store/bundles/flash-store.umd.js:4:53)
    at /bot/node_modules/flash-store/bundles/flash-store.umd.js:80:75
    at new Promise (<anonymous>)
    at __awaiter$1 (/bot/node_modules/flash-store/dist/flash-store.js:43:14)
    at FlashStore$1.delete (/bot/node_modules/flash-store/bundles/flash-store.umd.js:245:20)
    at FlashStoreSync.delete (/bot/node_modules/flash-store/bundles/flash-store.umd.js:850:53)
    at PadchatManager.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:295:41)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
14:00:36 ERR Config process.on(unhandledRejection) promise.catch(should use WXGetRoomPayload because get a room id :)
Config Error: should use WXGetRoomPayload because get a room id :
    at PadchatManager.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/padchat-rpc.ts:756:13)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:3:12)
    at PadchatManager.WXGetContactPayload (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:638:16)
    at PadchatManager.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:946:41)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:3:12)
    at config_1.retry (/bot/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:935:70)
    at /bot/node_modules/promise-retry/index.js:29:24
14:00:36 ERR Config process.on(unhandledRejection) promise.catch(should use WXGetRoomPayload because get a room id :)
Config Error: should use WXGetRoomPayload because get a room id :
    at PadchatManager.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/padchat-rpc.ts:756:13)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:3:12)
    at PadchatManager.WXGetContactPayload (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:638:16)
    at PadchatManager.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:946:41)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:3:12)
    at config_1.retry (/bot/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:935:70)
    at /bot/node_modules/promise-retry/index.js:29:24
(node:26) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
(node:26) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
```

**Comment by windmemory** [comment]
Don't remember why this happened. Close it for now.
