### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: no raw payload

### ISSUE THREAD

**Issue by zixia** [lijiarui/wechaty-puppet-padchat#139]
v0.9.16

```
2018-08-09T13:03:08.339663+00:00 app[web.1]: (node:20) UnhandledPromiseRejectionWarning: Error: no raw payload
2018-08-09T13:03:08.339667+00:00 app[web.1]:     at PadchatManager.<anonymous> (/app/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:1003:13)
2018-08-09T13:03:08.339669+00:00 app[web.1]:     at Generator.next (<anonymous>)
2018-08-09T13:03:08.339671+00:00 app[web.1]:     at fulfilled (/app/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
2018-08-09T13:03:08.339673+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
2018-08-09T13:03:08.339757+00:00 app[web.1]: (node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by windmemory** [comment]
@zixia Could you please keep an eye on this kind of error recently? If this happened again, please put the silly log here so we have a better track of how the data get loaded, and why the payload is not able to be retrieved. 

As I remember, we had fixed some paths that might cause this problem, but not sure we have done with all of the paths.

**Comment by zixia** [comment]
No problem, will let you know if i see it again
