### ISSUE TITLE
Message sent but still output error

### ISSUE THREAD

**Issue by kis87988** [lijiarui/wechaty-puppet-padchat#141]
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
docker run in container
wechaty-puppet-padchat@0.9.16

### Expected behavior
Send message without error

### Actual behavior
room-invite event not trigger 
message may sent but still get WxSendMsg Error

### Full Output Logs

```shell
$ docker create -t -i --name=$docker_name \
--mount type=bind,source="${dir}",target=/bot \
-e WECHATY_LOG=silly \
-e TZ="America/Los_Angeles" \
zixia/wechaty:latest mybot.ts
$ docker start -a $docker_name 
```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:
10:51:47 VERB Message constructor(3558483547345951002) for class Message
10:51:47 VERB Message ready()
10:51:47 VERB PuppetPadChat messageRawPayloadParser({msg_id="3558483547345951002"})
10:51:47 SILL PuppetPadchat messagePayload({"id":"3558483547345951002","timestamp":1533750706,"type":6,"fromId":"a38372624","text":"嗨","toId":"wxid_b19nbi9oqkpg12"})
10:51:47 SILL Contact ready() @ Puppet#0<PuppetPadchat>(Ponyo)/PuppetPadchat#0
10:51:47 SILL Contact ready() isReady() true
10:51:47 SILL Contact ready() @ Puppet#0<PuppetPadchat>(Ponyo)/PuppetPadchat#0
10:51:47 SILL Contact ready() isReady() true
10:51:47 VERB Wechaty ready()
10:51:47 VERB StateSwitch <WechatyReady> ready(on, false)
10:51:47 SILL StateSwitch <WechatyReady> ready(on, false) resolved.
10:51:47 SILL Wechaty ready() this.readyState.ready(on) resolved
10:51:47 VERB Contact friend()
10:51:47 SILL Contact alias()
10:51:47 SILL Contact alias()
10:51:47 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"","data":"","msgId":"","userId":"puppet_padchat_053716568dbc8f7c"}
10:51:48 VERB Message say(hi)
10:51:48 VERB PuppetPadchat messageSend({"contactId":"a38372624"}, hi)
10:51:48 SILL PadchatRpc rpcCall(WXSendMsg, ["a38372624","hi",""])
10:51:49 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXSendMsg","data":"","msgId":"-9007199254740939","userId":"puppet_padchat_053716568dbc8f
10:51:49 SILL PadchatRpc onServerMessagePadchat() discard empty payload.data for apiName: WXSendMsg
10:51:49 ERR Config ###########################
10:51:49 ERR Config unhandledRejection: Error: WXSendMsg error! canot get result from websocket server [object Promise]
10:51:49 ERR Config ###########################
10:51:49 ERR Config process.on(unhandledRejection) promise.catch(WXSendMsg error! canot get result from websocket server)
Config Error: WXSendMsg error! canot get result from websocket server
    at PadchatManager.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/padchat-rpc.ts:891:15)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
10:51:55 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"","data":"","msgId":"","userId":"puppet_padchat_053716568dbc8f7c"}
(node:26) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)
10:51:55 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"","data":"%5B%7B%22content%22%3A%22%E5%97%A8%22%2C%22continue%22%3A1%2C%22description%22
10:51:55 VERB PuppetPadchat onPadchatMessage({id=6313859546395743363, type=Text(5)})
10:51:55 VERB Message static create(6313859546395743363)
10:51:55 SILL Accessory #1316<Message> constructor()
10:51:55 VERB Message constructor(6313859546395743363) for class Message
10:51:55 VERB Message ready()
10:51:55 VERB PuppetPadChat messageRawPayloadParser({msg_id="6313859546395743363"})
10:51:55 SILL PuppetPadchat messagePayload({"id":"6313859546395743363","timestamp":1533750715,"type":6,"fromId":"a38372624","text":"嗨","toId":"wxid_b19nbi9oqkpg12"})
10:51:55 SILL Contact ready() @ Puppet#0<PuppetPadchat>(Ponyo)/PuppetPadchat#0
10:51:55 SILL Contact ready() isReady() true
10:51:55 SILL Contact ready() @ Puppet#0<PuppetPadchat>(Ponyo)/PuppetPadchat#0
10:51:55 SILL Contact ready() isReady() true
10:51:55 VERB Wechaty ready()
10:51:55 VERB StateSwitch <WechatyReady> ready(on, false)
10:51:55 SILL StateSwitch <WechatyReady> ready(on, false) resolved.
10:51:55 SILL Wechaty ready() this.readyState.ready(on) resolved
10:51:55 VERB Contact friend()
10:51:55 SILL Contact alias()
10:51:55 SILL Contact alias()
10:51:56 VERB Message say(嘿！)
10:51:56 VERB PuppetPadchat messageSend({"contactId":"a38372624"}, 嘿！)
10:51:56 SILL PadchatRpc rpcCall(WXSendMsg, ["a38372624","嘿！",""])
10:52:15 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(ws.on(message))
10:52:15 SILL PadchatRpc rpcCall(WXHeartBeat, [])
10:52:15 SILL PadchatRpc pre login rpcCall(WXHeartBeat, [])
10:52:16 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXHeartBeat","data":"%7B%22status%22%3A0%2C%22message%22%3A%22ok%22%7D","msgId":"-900719
10:52:16 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
10:52:16 SILL PuppetPadchat startWatchdog() padchatManager.on(heartbeat)
10:52:16 SILL Wechaty memoryCheck() free: 188 MB, require: 4 MB
10:52:16 SILL PadchatRpc WXHeartBeat result: {"status":0,"message":"ok"}
10:52:16 SILL PadchatRpc initWebSocket() ws.on(pong)
</details>

**Comment by windmemory** [comment]
Could you please help us check whether this issue is still happened recently?

**Comment by lijiarui** [comment]
ping @kis87988

**Comment by kis87988** [comment]
so far, I check 4 days log, none of them appear. I will close this for now.
I will still track this issue.

**Comment by windmemory** [comment]
Great, thanks for check this!
