### ISSUE TITLE
WebSocket reset can not be recovered automatically

### ISSUE THREAD

**Issue by zixia** [lijiarui/wechaty-puppet-padchat#160]
```
10:09:35 WARN PadchatRpc initWebSocket() ws.on(close) code: 1005, reason:
10:09:35 VERB PuppetPadchat startManager() manager.on(reconnect) for ws.on(close, 1005)
10:09:35 SILL PadchatRpc initWebSocket() Promise() ws.on(close)
10:09:36 VERB PuppetPadchat reconnect(), retry attempt left: 6
10:09:36 VERB PadchatRpc reconnect()
10:09:36 VERB PadchatRpc initWebSocket()
10:09:36 SILL PadchatRpc initWebSocket() Promise() ws.on(open)
10:09:36 SILL PadchatRpc rpcCall(init, [])
10:09:36 SILL PadchatRpc pre login rpcCall(init, [])
10:13:22 SILL Puppet constructor() watchdog.on(reset) reason: {"data":"ws.on(message)","timeout":240000}
10:13:22 SILL Puppet constructor() this.on(reset) reason: {"data":"ws.on(message)","timeout":240000}
10:13:22 SILL Puppet constructor() resetThrottleQueue.subscribe() reason: {"data":"ws.on(message)","timeout":240000}
10:13:22 VERB Puppet reset({"data":"ws.on(message)","timeout":240000})
10:13:22 SILL StateSwitch <PuppetPadchat> off() is false
10:13:22 VERB PuppetPadchat stop()
10:13:22 SILL StateSwitch <PuppetPadchat> off() is false
10:13:22 SILL StateSwitch <PuppetPadchat> off() is false
10:13:22 VERB StateSwitch <PuppetPadchat> off(pending) <- (false)
10:13:22 VERB PuppetPadchat logout()
10:13:22 SILL Contact ready() @ Puppet#0<PuppetPadchat>(ding-dong-bot)/PuppetPadchat#0
10:13:22 SILL Contact ready() isReady() true
10:13:22 VERB PuppetPadchatManager logout()
10:13:22 VERB PuppetPadchatManager releaseCache()
10:13:22 SILL PuppetPadchatManager releaseCache() closing caches ...
10:13:22 VERB ContactSelf name()
李卓桓 logouted
```

**Comment by zixia** [comment]
This problem occurred again when watchdog timeout.

```
19:47:40 SILL Puppet constructor() watchdog.on(reset) reason: {"data":"ws.on(message)","timeout":240000}
19:47:40 SILL Puppet constructor() this.on(reset) reason: {"data":"ws.on(message)","timeout":240000}
19:47:40 SILL Puppet constructor() resetThrottleQueue.subscribe() reason: {"data":"ws.on(message)","timeout":240000}
19:47:40 VERB Puppet reset({"data":"ws.on(message)","timeout":240000})
19:47:40 SILL StateSwitch <PuppetPadchat> off() is false
19:47:40 VERB PuppetPadchat stop()
19:47:40 SILL StateSwitch <PuppetPadchat> off() is false
19:47:40 SILL StateSwitch <PuppetPadchat> off() is false
19:47:40 VERB StateSwitch <PuppetPadchat> off(pending) <- (false)
19:47:40 VERB PuppetPadchat logout()
19:47:40 SILL Contact ready() @ Puppet#0<PuppetPadchat>(ding-dong-bot)/PuppetPadchat#0
19:47:40 SILL Contact ready() isReady() true
19:47:40 VERB PuppetPadchatManager logout()
19:47:40 VERB PuppetPadchatManager releaseCache()
19:47:40 SILL PuppetPadchatManager releaseCache() closing caches ...
19:47:40 VERB ContactSelf name()
李卓桓 logouted
```

**Comment by zixia** [comment]
All the above logs caused the Wechaty program exit at last.

**Comment by bitwater** [comment]
```
00:59:53 WARN PadchatRpc initWebSocket() ws.on(close) code: 1006, reason:
(node:20324) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.ping (/home/luomiao/caiyun-wechaty/node_modules/ws/lib/websocket.js:249:19)
    at WXHeartBeat.then.catch.finally (/home/luomiao/caiyun-wechaty/node_modules/wechaty-puppet-padchat/src/padchat-rpc.ts:419:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
00:59:53 WARN on-error onError(Error: Error: connect ENETUNREACH 54.223.73.175:8788)
00:59:53 WARN PadchatRpc initWebSocket() ws.on(close) code: 1006, reason:
00:59:58 WARN on-error onError(Error: Error: connect ENETUNREACH 54.223.73.175:8788)
00:59:58 WARN PadchatRpc initWebSocket() ws.on(close) code: 1006, reason:
01:00:03 WARN on-error onError(Error: Error: connect ENETUNREACH 54.223.73.175:8788)
01:00:03 WARN PadchatRpc initWebSocket() ws.on(close) code: 1006, reason:
```

**Comment by windmemory** [comment]
Seems like this is duplicate with https://github.com/lijiarui/wechaty-puppet-padchat/issues/163

Close for now, please reopen if this is not same issue as the issue pasted above.

**Comment by zixia** [comment]
No, it's not a duplicate.

In this issue, the puppet-padchat program exited after a WebSocket reset.
In the other issue, the puppet-padchat program got stuck after the WebSocket reset, because when `reset` event emitted, the puppet state is `off()`, which should be `on()` as I expected.

**Comment by windmemory** [comment]
Okay, thanks for the explanation.

**Comment by zixia** [comment]
@windmemory Yes, it's related with the flash-store.

According to https://github.com/zixia/flash-store/issues/13 , if we use `nosql-leveldb` then we will not get the segfault error. However, the `nosql-leveldb` requires the local build when install.

So at last, I switch it back to the `leveldown` which can just be installed without any compiling job, it will sometimes get the segfault error.

**Comment by zixia** [comment]
I can switch to use `nosql-leveldb` back.

So please feel free to let me know if you believe it's necessary.

**Comment by windmemory** [comment]
What if I switch the `FlashStoreSync` to `FlashStore`, will that solve the problem?

**Comment by windmemory** [comment]
Doesn't work :(

**Comment by windmemory** [comment]
Seems like we need to switch back to `nosql-leveldb`...

**Comment by zixia** [comment]
@windmemory Yes, please use flash-store@0.7 for your environment.

There are no much changes between the v0.7 with the latest version, except the nosql-leveldb related changes.

**Comment by windmemory** [comment]
Great! I will revert the version of `flash-store` back to `0.7`.

Thanks!
