### ISSUE TITLE
[ERROR] 房间邀请用户加入时报错

### ISSUE THREAD

**Issue by zhoumh1988** [lijiarui/wechaty-puppet-padchat#168]
```ssh
2018-08-29: 18:27:50 WARN PadchatRpc WXInviteChatRoomMember() status = 0 but message is not OK: 
2018-08-29: TypeError: Cannot read property 'big_head' of undefined
    at PuppetPadchat.<anonymous> (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:879:36)
    at Generator.next (<anonymous>)
    at /data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:21:12)
    at PuppetPadchat.roomMemberRawPayloadParser (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:876:16)
    at PuppetPadchat.<anonymous> (/data/projects/lightbot/node_modules/wechaty-puppet/dist/src/puppet.js:742:40)
    at Generator.next (<anonymous>)
    at fulfilled (/data/projects/lightbot/node_modules/wechaty-puppet/dist/src/puppet.js:22:58)
2018-08-29: 18:44:39 WARN PuppetPadchat messageFile(1920436073273254137)
2018-08-29: 19:50:46 WARN PuppetPadchat messageFile(2784509356476802634)
2018-08-29: Error: unknown jsonPayload sysmsg type: NewXmlChatRoomAccessVerifyApplication
    at Object.<anonymous> (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
2018-08-29: Error: unknown jsonPayload sysmsg type: NewXmlChatRoomAccessVerifyApplication
    at Object.<anonymous> (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
2018-08-29: (node:15621) UnhandledPromiseRejectionWarning: Error: no inviterId found
    at PuppetPadchat.<anonymous> (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:279:27)
    at Generator.next (<anonymous>)
    at fulfilled (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2018-08-29: (node:15621) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:15621) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-08-30: 02:59:45 WARN PadchatRpc initWebSocket() ws.on(close) code: 1005, reason: 
2018-08-30: 08:53:59 WARN PuppetPadchat messageFile(158118392937281574)
2018-08-30: 10:12:41 WARN PuppetPadchat messageFile(8939781671192075762)
2018-08-30: 10:12:41 WARN PuppetPadchat messageFile(305259697374215419)
2018-08-30: 12:00:23 WARN PadchatRpc initWebSocket() ws.on(close) code: 1005, reason: 
2018-08-30: 13:58:17 WARN PadchatRpc initWebSocket() ws.on(close) code: 1005, reason: 
2018-08-30: 13:58:41 WARN PadchatRpc initWebSocket() ws.on(close) code: 1005, reason: 
2018-08-30: Error: no inviterId found
    at PuppetPadchat.<anonymous> (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:279:27)
    at Generator.next (<anonymous>)
    at fulfilled (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2018-08-30: 15:14:34 WARN PadchatRpc initWebSocket() ws.on(close) code: 1005, reason: 
2018-08-30: 16:30:49 WARN PadchatRpc initWebSocket() ws.on(close) code: 1005, reason: 
2018-08-30: Error: no inviterId found
    at PuppetPadchat.<anonymous> (/data/projects/lightbot/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:279:27)
    at Generator.next (<anonymous>)
    at fulfilled (/data/projects/lightbot/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:22:58)
2018-08-30: 20:38:59 WARN PadchatRpc initWebSocket() ws.on(close) code: 1005, reason: 
2018-08-31: 00:00:15 WARN Room topic() room not ready
2018-08-31: (node:3708) UnhandledPromiseRejectionWarning: Error: not ready
    at AnotherOriginalClass.<anonymous> (/data/projects/lightbot/node_modules/wechaty/dist/src/user/room.js:598:23)
    at Generator.next (<anonymous>)
    at /data/projects/lightbot/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/data/projects/lightbot/node_modules/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.topic (/data/projects/lightbot/node_modules/wechaty/dist/src/user/room.js:594:16)
    at Query.queryRoomRandom (/data/projects/lightbot/lightbot.js:197:44)
    at Query.<anonymous> (/data/projects/lightbot/service/Query.js:22:25)
    at Query.<anonymous> (/data/projects/lightbot/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/data/projects/lightbot/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/data/projects/lightbot/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/data/projects/lightbot/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/data/projects/lightbot/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/data/projects/lightbot/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/data/projects/lightbot/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/data/projects/lightbot/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/data/projects/lightbot/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/data/projects/lightbot/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:638:20)
```

**Comment by kis87988** [comment]
same issue.
https://github.com/lijiarui/wechaty-puppet-padchat/issues/113

**Comment by windmemory** [comment]
@zhoumh1988 Could you please provide a reproduce steps for this error log? I would like to re-produce the issue then debug it.

**Comment by lijiarui** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
