### ISSUE TITLE
[ERROR]unknown jsonPayload sysmsg type: NewXmlChatRoomAccessVerifyApplication

### ISSUE THREAD

**Issue by zhoumh1988** [lijiarui/wechaty-puppet-padchat#174]
```
2018-09-06: Error: unknown jsonPayload sysmsg type: NewXmlChatRoomAccessVerifyApplication
    at Object.<anonymous> (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2018-09-06: Error: unknown jsonPayload sysmsg type: NewXmlChatRoomAccessVerifyApplication
    at Object.<anonymous> (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/data/projects/lightbot/node_modules/wechaty-puppet-padchat/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by lijiarui** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
