### ISSUE TITLE
login failed and got -106 status

### ISSUE THREAD

**Issue by xiamao** [lijiarui/wechaty-puppet-padchat#176]
after scan the login qrcode, login failed and got Error: PadchatRpc, WXQRCodeLogin, unknown status: -106

```
11:20:10 INFO Wechaty <Puppet#0<PuppetPadchat>()/PuppetPadchat#0> start() v0.21.10 is starting...
11:20:10 WARN PuppetPadchatManager startCheckScan() unknown WXCheckQRCodeStatus: -2
http://weixin.qq.com/x/wcLtEnZ0CaO4xD6bvHUU
[0] https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FwcLtEnZ0CaO4xD6bvHUU
Scan QR Code above to log in:
http://weixin.qq.com/x/wcLtEnZ0CaO4xD6bvHUU
[1] https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FwcLtEnZ0CaO4xD6bvHUU
Scan QR Code above to log in:
http://weixin.qq.com/x/wcLtEnZ0CaO4xD6bvHUU
[2] https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FwcLtEnZ0CaO4xD6bvHUU
Scan QR Code above to log in:
(node:27) UnhandledPromiseRejectionWarning: Error: PadchatRpc, WXQRCodeLogin, unknown status: -106
    at PadchatManager.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/padchat-rpc.ts:1051:11)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by QinYuanyuan** [comment]
这个问题什么时候可以解决呢？

**Comment by kis87988** [comment]
FYI: https://github.com/botorange/puppet-padchat-patch

**Comment by tianshunjian** [comment]
> FYI: https://github.com/botorange/puppet-padchat-patch

I clone the "wechaty-getting-started", and change the initial code of Wechaty to use padchat. I clone the puppet-padchat-patch, and copy the files of "src" to the "padchat-patch" which is the same level as "starter-bot.js". But the "import" causes an error.

 I want to know how to use the puppet-padchat-patch to avoid the issue -106.

There are my codes:
```
const { Wechaty } = require('wechaty')
import { PadchatPatch } from './padchat-patch' // this cause an error

const TOKEN = 'puppet_padchat_5199d122abca1920';
const initialName = 'test';
const puppet = 'wechaty-puppet-padchat'
const puppetOptions = {
    token: TOKEN
}
const bot = new Wechaty({
    initialName,
    puppet,
    puppetOptions,
});

bot.on('scan',    onScan)
bot.on('login',   onLogin)
bot.on('logout',  onLogout)
bot.on('message', onMessage)
```
The files path as below:
 
![image](https://user-images.githubusercontent.com/11658904/45743458-9e96ca80-bc2e-11e8-9735-27dd247c485f.png)

**Comment by lijiarui** [comment]
This issue has been fixed, please update the latest code and have a try.
