### ISSUE TITLE
on message report  #bug

### ISSUE THREAD

**Issue by typedef** [lijiarui/wechaty-puppet-padchat#195]
node:38) UnhandledPromiseRejectionWarning: Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/wechaty/node_modules/wechaty-puppet-padchat/src/padchat-rpc.ts:1495:13)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:38) UnhandledPromiseRejectionWarning: Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/wechaty/node_modules/wechaty-puppet-padchat/src/padchat-rpc.ts:1495:13)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

**Comment by lijiarui** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
