### ISSUE TITLE
在房间群发消息过程中报错

### ISSUE THREAD

**Issue by garrib** [lijiarui/wechaty-puppet-padchat#201]
### 0. Report Issue Guide

Please search in the issue first, and make sure your problem had not been reported before.

### 1. Provide Your Package Version
- What is your wechaty version?
Answer: "wechaty": "^0.22.4",

- What is your wechaty-puppet-padchat version?
Answer: "wechaty-puppet-padchat": "^0.16.2"

### 2. Expected behavior

**Question: What behavior do you expect?**

Answer: 接受到用户发的消息并在自己的群群发

### 3. Actual behavior

**Question: What actual behavior did you experience?**

Answer: 当我在实际测试中出现了几个经常出现的问题，并且我没有太好的办法判断问题出现的原因；
1. 重启时报错，错误码对应5.1；
2. 群发过程中报错，错误码对应5.2.我是在群消息监听事件中出现这个错误的，此时我的逻辑还没有跑完。**并且**：出现错误后尝试重启机器人，在没有其他操作时，只要触发监听事件，之前的信息还会继续发送。我认为是在我产生错误时，你们这边的缓存没有得到释放，所以当我重启时会继续向Wechat推送之前的消息。这在我测试的过程中产生了非常多不必要的麻烦。
3. 有时候群发消息的速度很慢，是否是我申请测试的Token有限制。

### 4. Steps to reproduce your problem (and fixes, if any)

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**Question: What're the reproducible steps for us to see your problem?**

Answer: 我进行的操作有：收到用户请求发的报名消息，在指定id的群转发，收到特定信息后再次在这些群发送接龙消息

### 5. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

1. Error: WXSendMsg error! canot get result from websocket server
    at PadchatManager.<anonymous> (D:\Project\mine\thinkraz-wxrobot-component\node_modules\wechaty-puppet-padchat\src\padchat-rpc.ts:958:15)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Project\mine\thinkraz-wxrobot-component\node_modules\wechaty-puppet-padchat\dist\src\padchat-rpc.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

2. Error: no raw payload 
    at PadchatManager.<anonymous> (D:\Project\mine\thinkraz-wxrobot-component\node_modules\wechaty-puppet-padchat\src\padchat-manager.ts:1044:13)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Project\mine\thinkraz-wxrobot-component\node_modules\wechaty-puppet-padchat\dist\src\padchat-manager.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
17:33:16 ERR Wechaty start() exception: no raw payload
(node:5304) UnhandledPromiseRejectionWarning: Error: no raw payload
    at PadchatManager.<anonymous> (D:\Project\mine\thinkraz-wxrobot-component\node_modules\wechaty-puppet-padchat\src\padchat-manager.ts:1044:13)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Project\mine\thinkraz-wxrobot-component\node_modules\wechaty-puppet-padchat\dist\src\padchat-manager.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5304) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

</details>

**Comment by windmemory** [comment]
初步判断，问题的根源是发送消息过快，导致微信中断连接

---

首先，wechaty在每次启动的时候，（无论是第一次启动，还是重启）都会加载最近的几条消息，这也是微信的机制。这个时候可能会迅速加载几条之前的消息（几毫秒内完成），可能这些消息都是会触发你这边的监听事件，然后你这边就会在很短的时间内触发发送多条消息。

> 我进行的操作有：收到用户请求发的报名消息，在指定id的群转发，收到特定信息后再次在这些群发送接龙消息

从这个描述中，我的理解是，用户的一个消息，会触发你这边发送多条消息，这样的话，在启动的时候如果接收到多条，那么瞬间会发出成倍数量的消息，这样很可能会有问题，导致微信中断连接。

我的建议是，增加一个消息队列，并且对接收到的消息做缓存处理，消息队列做有间隔的发送消息，缓存消息避免在服务重启的时候对同一条消息执行两次或多次响应

**Comment by kis87988** [comment]
補充一點: 我建議可以在code中必要的地方放ready() checker.

**Comment by CherryBoomBoom** [comment]
我将发送消息的时间间隔设置成一秒，并加上过滤器有了一定的效果，谢谢你们

**Comment by windmemory** [comment]
不用谢，如果没什么问题了，麻烦关闭这个issue吧。
