### ISSUE TITLE
经常报错以下warning获取不到信息

### ISSUE THREAD

**Issue by typedef** [lijiarui/wechaty-puppet-padchat#204]
### 0. Report Issue Guide

Please search in the issue first, and make sure your problem had not been reported before.

### 1. Provide Your Package Version
- What is your wechaty version?
Answer:
<wechaty-puppet-padchat>  v0.23.17 

- What is your wechaty-puppet-padchat version?
Answer:

### 2. Expected behavior

**Question: What behavior do you expect?**

Answer:

### 3. Actual behavior

**Question: What actual behavior did you experience?**

Answer:

### 4. Steps to reproduce your problem (and fixes, if any)

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**Question: What're the reproducible steps for us to see your problem?**

Answer:

### 5. Full Output Logs

<details>
<summary>
(node:1818) UnhandledPromiseRejectionWarning: Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:1335:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:1818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 86)
10:08:33 WARN PuppetPadchat messageFile(2296763595448356121)
(node:1818) UnhandledPromiseRejectionWarning: Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:1335:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:1818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 87)
10:08:34 WARN PuppetPadchat messageFile(6224845306862463221)
(node:1818) UnhandledPromiseRejectionWarning: Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:1335:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:1818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 88)
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

**Comment by lijiarui** [comment]
Need More Info.
