### ISSUE TITLE
token复用顶号时没有回调通知，并且似乎有未处理异常

### ISSUE THREAD

**Issue by fatfatson** [lijiarui/wechaty-puppet-padchat#217]
### 1. 提供你的包版本信息
- wechaty 版本：v0.22.4
- wechaty-puppet-padchat 版本：v0.22.4 
- node 版本： v10.11.0

### 2. 期待程序运行的结果
顶号时，老连接收到回调通知

### 3. 程序实际运行的结果
没有回调，并且报未处理异常

### 4. 复现的步骤 (或者解决的步骤)
使用同一token登录两次，第一个连接上就会出现

### 5. 完整的日志信息：
**请提供完整的日志信息(不要只提供部分的日志内容！)**
<details>
<summary>
[api] [Node] 19:08:01 INFO Wechaty <wechaty-puppet-padchat> start() v0.22.4 is starting...
[api] [Node] 12/4/2018, 7:08:01 PM [Agt] info: starting bot, Yr1FWQNZ
[api] [Node] 12/4/2018, 7:08:01 PM [Cli] info: subagent, pok4W_cn-QRdWBCJAAAB, Yr1FWQNZ
[api] [Node] 19:08:02 WARN PadchatRpc initWebSocket() ws.on(close) code: 3001, reason: This connection is kicked out by another connection, please check the token you are using.
[api] [Node] 12/4/2018, 7:08:02 PM [Agt] info: started, Yr1FWQNZ
[api] [Node] 19:08:02 WARN PuppetPadchatManager startCheckScan() unknown WXCheckQRCodeStatus: -2
[api] [Node] 19:08:02 WARN PadchatRpc initWebSocket() ws.on(close) code: 3001, reason: This connection is kicked out by another connection, please check the token you are using.
[api] [Node] 19:08:03 WARN PuppetPadchatManager startCheckScan() checkScanLoop() exception: Error: WebSocket is not open: readyState 3 (CLOSED)
[api] [Node] 19:08:03 WARN PuppetPadchat startManager() manager.on(reset) for startCheckScan() checkScanLoop() exception. Restarting PuppetPadchat ...
[api] [Node] 19:08:03 WARN PuppetPadchat logout() this.id not exist
[api] [Node] 19:08:03 WARN PadchatRpc initWebSocket() ws.on(close) code: 3001, reason: This connection is kicked out by another connection, please check the token you are using.
[api] [Node] 19:08:03 WARN PuppetPadchatManager startCheckScan() unknown WXCheckQRCodeStatus: -2
[api] [Node] 12/4/2018, 7:08:04 PM [Cli] info: onscan, 1, 1, http://weixin.qq.com/x/YdUKIeiY6amD-Z72wMiE, pok4W_cn-QRdWBCJAAAB
[api] [Node] (node:14196) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 3 (CLOSED)
[api] [Node]     at WebSocket.send (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/node_modules/ws/lib/websocket.js:314:19)
[api] [Node]     at Peer.jsonRpc.on (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:144:29)
[api] [Node]     at Peer.emit (events.js:182:13)
[api] [Node]     at Peer.EventEmitter.emit (domain.js:442:20)
[api] [Node]     at Peer.push (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/json-rpc-peer/dist/index.js:271:52)
[api] [Node]     at /Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/json-rpc-peer/dist/index.js:199:14
[api] [Node]     at new Promise (<anonymous>)
[api] [Node]     at Peer.request (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/json-rpc-peer/dist/index.js:196:12)
[api] [Node]     at Promise (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:417:38)
[api] [Node]     at new Promise (<anonymous>)
[api] [Node]     at PadchatManager.<anonymous> (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:416:28)
[api] [Node]     at Generator.next (<anonymous>)
[api] [Node]     at /Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:7:71
[api] [Node]     at new Promise (<anonymous>)
[api] [Node]     at __awaiter (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:3:12)
[api] [Node]     at PadchatManager.rpcCall (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:405:16)
[api] [Node]     at PadchatManager.<anonymous> (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:718:39)
[api] [Node]     at Generator.next (<anonymous>)
[api] [Node]     at /Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:7:71
[api] [Node]     at new Promise (<anonymous>)
[api] [Node]     at __awaiter (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:3:12)
[api] [Node]     at PadchatManager.WXSyncContact (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:717:16)
[api] [Node]     at PadchatManager.<anonymous> (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:685:52)
[api] [Node]     at Generator.next (<anonymous>)
[api] [Node]     at fulfilled (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
[api] [Node] (node:14196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[api] [Node] (node:14196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[api] [Node] (node:14196) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 3 (CLOSED)
[api] [Node]     at WebSocket.ping (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/node_modules/ws/lib/websocket.js:249:19)
[api] [Node]     at WXHeartBeat.then.catch.finally (/Users/wellbye/git-repo/j/wxd/server/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:299:24)
[api] [Node]     at <anonymous>
[api] [Node] (node:14196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

**Comment by lijiarui** [comment]
重启后这个问题还存在么？
