### ISSUE TITLE
Bot error: Error: Error: getaddrinfo ENOTFOUND padchat.botorange.com padchat.botorange.com:80

### ISSUE THREAD

**Issue by huan** [lijiarui/wechaty-puppet-padchat#230]
I got this network error recently, and after that, the bot stop response anymore.

```ts
李卓桓 logouted
12:49:56 VERB PuppetPadchatManager startCheckScan()
12:49:56 VERB PuppetPadchatManager stop()
12:49:56 WARN PuppetPadchatManager stop() subscript not exist
12:49:56 VERB PuppetPadchatManager stopCheckScan()
12:49:56 VERB PadchatRpc stop()
12:49:56 VERB PadchatRpc stopQueues()
12:49:56 VERB PuppetPadchatManager releaseCache()
12:49:56 VERB PuppetPadchatManager releaseCache() cache not exist.
12:49:56 VERB StateSwitch <PuppetPadchat> off(true) <- (pending)
12:49:56 VERB PuppetPadchat start() with ding-dong-bot
12:49:56 VERB StateSwitch <PuppetPadchat> on(pending) <- (false)
12:49:56 VERB PadchatRpc constructor(ws://padchat.botorange.com/wx, puppet_padchat_e6ec95f88f7059c0)
12:49:56 VERB PuppetPadchatManager constructor()
12:49:56 VERB PuppetPadchat startManager()
12:49:56 VERB PuppetPadchatManager start()
12:49:56 VERB PadchatRpc start()
12:49:56 VERB PadchatRpc initWebSocket()
12:50:23 VERB PadchatRpc initWebSocket() ws.on(error) Error: getaddrinfo ENOTFOUND padchat.botorange.com padchat.botorange.com:80
Bot error: Error: Error: getaddrinfo ENOTFOUND padchat.botorange.com padchat.botorange.com:80
    at PuppetPadchat.puppet.on.error (/home/ubuntu/workspace/src/wechaty.ts:602:32)
    at PuppetPadchat.emit (events.js:182:13)
    at PuppetPadchat.EventEmitter.emit (domain.js:442:20)
    at PuppetPadchat.emit (/home/ubuntu/workspace/node_modules/wechaty-puppet/src/puppet.ts:292:18)
    at PadchatManager.manager.on.e (/home/ubuntu/workspace/node_modules/wechaty-puppet-padchat/src/puppet-padchat.ts:232:83)
    at PadchatManager.emit (events.js:182:13)
    at PadchatManager.EventEmitter.emit (domain.js:442:20)
    at WebSocket.ws.on.e (/home/ubuntu/workspace/node_modules/wechaty-puppet-padchat/src/padchat-rpc.ts:296:14)
    at WebSocket.emit (events.js:187:15)
    at WebSocket.EventEmitter.emit (domain.js:442:20)
    at ClientRequest.req.on (/home/ubuntu/workspace/node_modules/ws/lib/websocket.js:528:10)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
12:50:23 WARN PadchatRpc initWebSocket() ws.on(close) code: 1006, reason: 
12:50:23 WARN PadchatRpc initWebSocket() ws.on(close) reconnectThrottleQueue not exist
12:50:23 WARN PuppetPadchatManager start() super.start() exception: undefined
12:50:23 VERB PadchatRpc stop()
12:50:23 VERB PadchatRpc stopQueues()
12:50:23 WARN PadchatRpc stop() subscript not exist
12:50:23 WARN PadchatRpc stop() no socket
12:50:24 WARN PuppetPadchatManager start() super.start() retry now ...
12:50:24 VERB PadchatRpc start()
12:50:24 VERB PadchatRpc initWebSocket()
12:51:10 VERB PadchatRpc initJsonRpc()
12:51:10 VERB PadchatRpc startQueues()
12:51:10 VERB PadchatRpc initHeartbeat()
12:51:19 VERB PadchatRpc WXInitialize()
12:51:21 VERB MemoryCard <puppet> get(WECHATY_PUPPET_PADCHAT)
12:51:21 VERB PuppetPadchatManager tryLoad62Data()
```

**Comment by windmemory** [comment]
Could you please try with [`wechaty-puppet-padpro`](https://github.com/botorange/wechaty-puppet-padpro)

And let's see whether similar issues happened with that `puppet`

**Comment by windmemory** [comment]
Can you reproduce this issue consistently?

**Comment by huan** [comment]
Let's make it clear: it's a dns related problem. 

Please feel free to reopen it if you experience similar problems.
