### ISSUE TITLE
你已成为新群主

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#44]
```
22:09:21 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"%5B%7B%22content%22%3A%22%E4%BD%A0%E5%B7%B2%E6%88%90%E4%B8%BA%E6%96%B0%E7%BE%A4%E4%B8%BB%22%2C%22continue%22%3A1%2C%22description%22%3A%22%22%2C%22from_user%22%3A%226350854677%40chatroom%22%2C%22msg_id%22%3A%223798725634572049107%22%2C%22msg_source%22%3A%22%22%2C%22msg_type%22%3A5%2C%22status%22%3A1%2C%22sub_type%22%3A10000%2C%22timestamp%22%3A1527689361%2C%22to_user%22%3A%22wxid_zj2cahpwzgie12%22%2C%22uin%22%3A324216852%7D%5D%0A","msgId":"","userId":"padchattest"}
22:09:21 SILL PuppetPadchat WebSocket Server rawData result: {"content":"你已成为新群主","continue":1,"description":"","from_user":"6350854677@chatroom","msg_id":"3798725634572049107","msg_source":"","msg_type":5,"status":1,"sub_type":10000,"timestamp":1527689361,"to_user":"wxid_zj2cahpwzgie12","uin":324216852}
22:09:21 SILL PuppetAccessory #15<Room<undefined>> constructor()
22:09:21 SILL Room constructor(6350854677@chatroom)
22:09:21 SILL PuppetAccessory #15<Room<undefined>> get puppet()
22:09:21 SILL PuppetAccessory <Room> static get puppet()
22:09:21 SILL PuppetAccessory #16<Contact> constructor()
22:09:21 SILL Contact constructor(你已成为新群主)
22:09:21 SILL PuppetAccessory #16<Contact> get puppet()
22:09:21 SILL PuppetAccessory <Contact> static get puppet()
22:09:21 VERB Room ready()
22:09:21 SILL PuppetAccessory #15<Room<undefined>> get puppet()
22:09:21 SILL PuppetAccessory <Room> static get puppet()
22:09:21 VERB Puppet roomPayload(6350854677@chatroom)
22:09:21 VERB PuppetPadchat roomRawPayload(6350854677@chatroom)
22:09:21 SILL PuppetPadchatBridge sendToWebSocket: {"userId":"padchattest","msgId":"cjht6svqs000jlswdaootkg3x","apiName":"WXGetContact","param":["6350854677%40chatroom"]}
22:09:22 SILL PuppetPadchat return apiName: WXGetContact, msgId: cjht6svqs000jlswdaootkg3x
22:09:22 VERB PuppetPadchat roomRawPayloadParser([object Object])
22:09:22 SILL PuppetAccessory #17<Contact> constructor()
22:09:22 SILL Contact constructor(mengjunjun001)
22:09:22 SILL PuppetAccessory #17<Contact> get puppet()
22:09:22 SILL PuppetAccessory <Contact> static get puppet()
22:09:22 SILL PuppetAccessory #18<Contact> constructor()
22:09:22 SILL Contact constructor(wxid_7708837087612)
22:09:22 SILL PuppetAccessory #18<Contact> get puppet()
22:09:22 SILL PuppetAccessory <Contact> static get puppet()
22:09:22 SILL PuppetAccessory #2<Contact> get puppet()
22:09:22 SILL PuppetAccessory <Contact> static get puppet()
22:09:22 SILL Contact ready() @ PuppetPadchat<default>
22:09:22 SILL Contact ready() isReady() true
22:09:22 SILL PuppetAccessory #17<Contact> get puppet()
22:09:22 SILL PuppetAccessory <Contact> static get puppet()
22:09:22 SILL Contact ready() @ PuppetPadchat<default>
22:09:22 SILL PuppetAccessory #17<Contact> get puppet()
22:09:22 SILL PuppetAccessory <Contact> static get puppet()
22:09:22 SILL Puppet contactPayload(mengjunjun001) @ PuppetPadchat<default>
22:09:22 VERB PuppetPadchat contactRawPayload(mengjunjun001)
22:09:22 SILL PuppetPadchatBridge sendToWebSocket: {"userId":"padchattest","msgId":"cjht6sw07000klswdijbj0dwl","apiName":"WXGetContact","param":["mengjunjun001"]}
22:09:22 SILL PuppetAccessory #1<Contact> get puppet()
22:09:22 SILL PuppetAccessory <Contact> static get puppet()
22:09:22 SILL Contact ready() @ PuppetPadchat<default>
22:09:22 SILL Contact ready() isReady() true
22:09:22 SILL PuppetAccessory #18<Contact> get puppet()
22:09:22 SILL PuppetAccessory <Contact> static get puppet()
22:09:22 SILL Contact ready() @ PuppetPadchat<default>
22:09:22 SILL PuppetAccessory #18<Contact> get puppet()
22:09:22 SILL PuppetAccessory <Contact> static get puppet()
22:09:22 SILL Puppet contactPayload(wxid_7708837087612) @ PuppetPadchat<default>
22:09:22 VERB PuppetPadchat contactRawPayload(wxid_7708837087612)
22:09:22 SILL PuppetPadchatBridge sendToWebSocket: {"userId":"padchattest","msgId":"cjht6sw08000llswdz9b6hpsn","apiName":"WXGetContact","param":["wxid_7708837087612"]}
22:09:22 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:09:22 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:09:22 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:09:22 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:09:22 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:09:22 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:09:22 SILL PuppetPadchat return apiName: WXGetContact, msgId: cjht6sw07000klswdijbj0dwl
22:09:22 VERB PuppetPadchat contactRawPayloadParser([object Object])
22:09:22 SILL Contact alias()
22:09:22 SILL Contact ready() this.puppet.contactPayload(Contact<女儿>) resolved
22:09:22 SILL PuppetPadchat return apiName: WXGetContact, msgId: cjht6sw08000llswdz9b6hpsn
22:09:22 VERB PuppetPadchat contactRawPayloadParser([object Object])
22:09:22 SILL Contact alias()
22:09:22 SILL Contact ready() this.puppet.contactPayload(Contact<王宁>) resolved
22:09:22 SILL PuppetPadchatBridge sendToWebSocket: {"userId":"padchattest","msgId":"cjht6swdj000mlswd74cv58yu","apiName":"WXGetChatRoomMember","param":["6350854677%40chatroom"]}
22:09:23 SILL PuppetPadchat return apiName: WXGetChatRoomMember, msgId: cjht6swdj000mlswd74cv58yu
22:09:23 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:09:23 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:09:23 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:09:23 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:09:23 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"%5B%7B%22continue%22%3A0%2C%22msg_type%22%3A32768%2C%22status%22%3A1%2C%22uin%22%3A324216852%7D%5D%0A","msgId":"","userId":"padchattest"}
22:09:23 SILL PuppetPadchat WebSocket Server rawData result: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
22:09:23 SILL PuppetPadchat WebSocket Server: get empty message msg_id form Tencent server
22:09:23 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:09:23 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:09:23 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:09:23 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:09:23 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:09:23 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:09:23 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:09:23 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:09:23 VERB PuppetPadchat roomParseMap(name, memberList.length=4)
22:09:23 VERB PuppetPadchat roomParseMap(roomAlias, memberList.length=4)
22:09:23 VERB PuppetPadchat roomParseMap(contactAlias, memberList.length=4)
22:09:23 SILL Contact alias()
22:09:23 SILL Contact alias()
22:09:23 SILL Contact alias()
22:09:23 SILL Contact alias()
22:09:23 SILL PuppetAccessory #15<Room<undefined>> get puppet()
22:09:23 SILL PuppetAccessory <Room> static get puppet()
22:09:23 SILL PuppetAccessory #15<Room<undefined>> get puppet()
22:09:23 SILL PuppetAccessory <Room> static get puppet()
22:09:23 SILL PuppetAccessory #15<Room<undefined>> get puppet()
22:09:23 SILL PuppetAccessory <Room> static get puppet()
22:09:23 SILL PuppetAccessory #15<Room<undefined>> get puppet()
22:09:23 SILL PuppetAccessory <Room> static get puppet()
22:09:23 SILL PuppetAccessory #2<Contact> get puppet()
22:09:23 SILL PuppetAccessory <Contact> static get puppet()
22:09:23 SILL Contact ready() @ PuppetPadchat<default>
22:09:23 SILL Contact ready() isReady() true
22:09:23 SILL PuppetAccessory #17<Contact> get puppet()
22:09:23 SILL PuppetAccessory <Contact> static get puppet()
22:09:23 SILL Contact ready() @ PuppetPadchat<default>
22:09:23 SILL Contact ready() isReady() true
22:09:23 SILL PuppetAccessory #1<Contact> get puppet()
22:09:23 SILL PuppetAccessory <Contact> static get puppet()
22:09:23 SILL Contact ready() @ PuppetPadchat<default>
22:09:23 SILL Contact ready() isReady() true
22:09:23 SILL PuppetAccessory #18<Contact> get puppet()
22:09:23 SILL PuppetAccessory <Contact> static get puppet()
22:09:23 SILL Contact ready() @ PuppetPadchat<default>
22:09:23 SILL Contact ready() isReady() true
22:09:23 SILL PuppetAccessory #16<Contact> get puppet()
22:09:23 SILL PuppetAccessory <Contact> static get puppet()
22:09:23 SILL Contact ready() @ PuppetPadchat<default>
22:09:23 SILL PuppetAccessory #16<Contact> get puppet()
22:09:23 SILL PuppetAccessory <Contact> static get puppet()
22:09:23 SILL Puppet contactPayload(你已成为新群主) @ PuppetPadchat<default>
22:09:23 VERB PuppetPadchat contactRawPayload(你已成为新群主)
22:09:23 SILL PuppetPadchatBridge sendToWebSocket: {"userId":"padchattest","msgId":"cjht6swrj000nlswdf5sihd9i","apiName":"WXGetContact","param":["%E4%BD%A0%E5%B7%B2%E6%88%90%E4%B8%BA%E6%96%B0%E7%BE%A4%E4%B8%BB"]}
22:09:23 SILL PuppetPadchat return apiName: WXGetContact, msgId: cjht6swrj000nlswdf5sihd9i
22:09:23 WARN PuppetPadchatBridge WXGetContact cannot get user_name, id: 你已成为新群主
22:09:23 VERB PuppetPadchat contactRawPayloadParser([object Object])
22:09:23 ERR Contact ready() this.puppet.contactPayload(Contact) exception: cannot get user_name(wxid)!
22:09:23 ERR Config ###########################
22:09:23 ERR Config unhandledRejection: Error: cannot get user_name(wxid)! [object Promise]
22:09:23 ERR Config ###########################
22:09:23 ERR Config process.on(unhandledRejection) promise.catch(cannot get user_name(wxid)!)
Config Error: cannot get user_name(wxid)!
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:557:13)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:21:12)
    at PuppetPadchat.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:418:16)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:402:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:16336) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)

```

**Comment by zixia** [comment]
Should fixed in the current version.

**Comment by lijiarui** [comment]
fixed
