### ISSUE TITLE
Contact id 切割错误异常

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#46]
```
22:11:02 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"%5B%7B%22content%22%3A%22%E4%BD%A0%E5%B0%86%5C%22wechaty-alias%5C%22%E7%A7%BB%E5%87%BA%E4%BA%86%E7%BE%A4%E8%81%8A%22%2C%22continue%22%3A1%2C%22description%22%3A%22%22%2C%22from_user%22%3A%226350854677%40chatroom%22%2C%22msg_id%22%3A%222333583612218403809%22%2C%22msg_source%22%3A%22%22%2C%22msg_type%22%3A5%2C%22status%22%3A1%2C%22sub_type%22%3A10000%2C%22timestamp%22%3A1527689462%2C%22to_user%22%3A%22wxid_zj2cahpwzgie12%22%2C%22uin%22%3A324216852%7D%5D%0A","msgId":"","userId":"padchattest"}
22:11:02 SILL PuppetPadchat WebSocket Server rawData result: {"content":"你将\"wechaty-alias\"移出了群聊","continue":1,"description":"","from_user":"6350854677@chatroom","msg_id":"2333583612218403809","msg_source":"","msg_type":5,"status":1,"sub_type":10000,"timestamp":1527689462,"to_user":"wxid_zj2cahpwzgie12","uin":324216852}
22:11:02 SILL PuppetAccessory #20<Contact> constructor()
22:11:02 SILL Contact constructor(你将"wechaty-alias"移出了群聊)
22:11:02 SILL PuppetAccessory #20<Contact> get puppet()
22:11:02 SILL PuppetAccessory <Contact> static get puppet()
22:11:02 VERB Room ready()
22:11:02 SILL PuppetAccessory #20<Contact> get puppet()
22:11:02 SILL PuppetAccessory <Contact> static get puppet()
22:11:02 SILL Contact ready() @ PuppetPadchat<default>
22:11:02 SILL PuppetAccessory #20<Contact> get puppet()
22:11:02 SILL PuppetAccessory <Contact> static get puppet()
22:11:02 SILL Puppet contactPayload(你将"wechaty-alias"移出了群聊) @ PuppetPadchat<default>
22:11:02 VERB PuppetPadchat contactRawPayload(你将"wechaty-alias"移出了群聊)
22:11:02 SILL PuppetPadchatBridge sendToWebSocket: {"userId":"padchattest","msgId":"cjht6v1k3000plswd1l57a6og","apiName":"WXGetContact","param":["%E4%BD%A0%E5%B0%86%22wechaty-alias%22%E7%A7%BB%E5%87%BA%E4%BA%86%E7%BE%A4%E8%81%8A"]}
22:11:02 SILL PuppetPadchat return apiName: WXGetContact, msgId: cjht6v1k3000plswd1l57a6og
22:11:02 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:11:02 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:11:02 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:11:02 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:11:02 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"","msgId":"","userId":"padchattest"}
22:11:02 SILL PuppetPadchat WebSocket Server get empty message data form Tencent server
22:11:02 WARN PuppetPadchatBridge WXGetContact cannot get user_name, id: 你将"wechaty-alias"移出了群聊
22:11:02 VERB PuppetPadchat contactRawPayloadParser([object Object])
22:11:02 ERR Contact ready() this.puppet.contactPayload(Contact) exception: cannot get user_name(wxid)!
22:11:02 ERR Config ###########################
22:11:02 ERR Config unhandledRejection: Error: cannot get user_name(wxid)! [object Promise]
22:11:02 ERR Config ###########################
22:11:02 ERR Config process.on(unhandledRejection) promise.catch(cannot get user_name(wxid)!)
Config Error: cannot get user_name(wxid)!
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:557:13)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:21:12)
    at PuppetPadchat.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:418:16)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:402:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by zixia** [comment]
This issue should have been fixed in the last commits.

**Comment by lijiarui** [comment]
fixed
