### ISSUE TITLE
SYS 群主已启用群聊邀请确认

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#50]
```
22:35:03 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"%5B%7B%22content%22%3A%22%E7%BE%A4%E4%B8%BB%E5%B7%B2%E5%90%AF%E7%94%A8%E2%80%9C%E7%BE%A4%E8%81%8A%E9%82%80%E8%AF%B7%E7%A1%AE%E8%AE%A4%E2%80%9D%EF%BC%8C%E7%BE%A4%E6%88%90%E5%91%98%E9%9C%80%E7%BE%A4%E4%B8%BB%E7%A1%AE%E8%AE%A4%E6%89%8D%E8%83%BD%E9%82%80%E8%AF%B7%E6%9C%8B%E5%8F%8B%E8%BF%9B%E7%BE%A4%E3%80%82%22%2C%22continue%22%3A1%2C%22description%22%3A%22%22%2C%22from_user%22%3A%226350854677%40chatroom%22%2C%22msg_id%22%3A%2230689102286337417%22%2C%22msg_source%22%3A%22%22%2C%22msg_type%22%3A5%2C%22status%22%3A1%2C%22sub_type%22%3A10000%2C%22timestamp%22%3A1527690902%2C%22to_user%22%3A%22wxid_zj2cahpwzgie12%22%2C%22uin%22%3A324216852%7D%5D%0A","msgId":"","userId":"padchattest"}
22:35:03 SILL PuppetPadchat WebSocket Server rawData result: {"content":"群主已启用“群聊邀请确认”，群成员需群主确认才能邀请朋友进群。","continue":1,"description":"","from_user":"6350854677@chatroom","msg_id":"30689102286337417","msg_source":"","msg_type":5,"status":1,"sub_type":10000,"timestamp":1527690902,"to_user":"wxid_zj2cahpwzgie12","uin":324216852}
22:35:03 VERB Room ready()
22:35:03 SILL PuppetAccessory #4<Contact> get puppet()
22:35:03 SILL PuppetAccessory <Contact> static get puppet()
22:35:03 SILL Contact ready() @ PuppetPadchat<default>
22:35:03 SILL PuppetAccessory #4<Contact> get puppet()
22:35:03 SILL PuppetAccessory <Contact> static get puppet()
22:35:03 SILL Puppet contactPayload(群主已启用“群聊邀请确认”，群成员需群主确认才能邀请朋友进群。) @ PuppetPadchat<default>
22:35:03 VERB PuppetPadchat contactRawPayload(群主已启用“群聊邀请确认”，群成员需群主确认才能邀请朋友进群。)
22:35:03 SILL PuppetPadchatBridge sendToWebSocket: {"userId":"padchattest","msgId":"cjht7px7d000pp6wd5jlt0l9o","apiName":"WXGetContact","param":["%E7%BE%A4%E4%B8%BB%E5%B7%B2%E5%90%AF%E7%94%A8%E2%80%9C%E7%BE%A4%E8%81%8A%E9%82%80%E8%AF%B7%E7%A1%AE%E8%AE%A4%E2%80%9D%EF%BC%8C%E7%BE%A4%E6%88%90%E5%91%98%E9%9C%80%E7%BE%A4%E4%B8%BB%E7%A1%AE%E8%AE%A4%E6%89%8D%E8%83%BD%E9%82%80%E8%AF%B7%E6%9C%8B%E5%8F%8B%E8%BF%9B%E7%BE%A4%E3%80%82"]}
22:35:03 SILL PuppetPadchat return apiName: WXGetContact, msgId: cjht7px7d000pp6wd5jlt0l9o
22:35:03 WARN PuppetPadchatBridge WXGetContact cannot get user_name, id: 群主已启用“群聊邀请确认”，群成员需群主确认才能邀请朋友进群。
22:35:03 VERB PuppetPadchat contactRawPayloadParser([object Object])
22:35:03 ERR Contact ready() this.puppet.contactPayload(Contact) exception: cannot get user_name(wxid)!
22:35:03 ERR Config ###########################
22:35:03 ERR Config unhandledRejection: Error: cannot get user_name(wxid)! [object Promise]
22:35:03 ERR Config ###########################
22:35:03 ERR Config process.on(unhandledRejection) promise.catch(cannot get user_name(wxid)!)
Config Error: cannot get user_name(wxid)!
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:557:13)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:21:12)
    at PuppetPadchat.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:418:16)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:402:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:21642) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 12)
22:35:04 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"%5B%7B%22continue%22%3A0%2C%22msg_type%22%3A32768%2C%22status%22%3A1%2C%22uin%22%3A324216852%7D%5D%0A","msgId":"","userId":"padchattest"}
22:35:04 SILL PuppetPadchat WebSocket Server rawData result: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
22:35:04 SILL PuppetPadchat WebSocket Server: get empty message msg_id form Tencent server
```

**Comment by zixia** [comment]
Should have been fixed today.

**Comment by lijiarui** [comment]
fix
