### ISSUE TITLE
SYS 群主已回复默认进群方式

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#51]
```
22:35:51 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"%5B%7B%22content%22%3A%22%E7%BE%A4%E4%B8%BB%E5%B7%B2%E6%81%A2%E5%A4%8D%E9%BB%98%E8%AE%A4%E8%BF%9B%E7%BE%A4%E6%96%B9%E5%BC%8F%E3%80%82%22%2C%22continue%22%3A1%2C%22description%22%3A%22%22%2C%22from_user%22%3A%226350854677%40chatroom%22%2C%22msg_id%22%3A%224838179978529771707%22%2C%22msg_source%22%3A%22%22%2C%22msg_type%22%3A5%2C%22status%22%3A1%2C%22sub_type%22%3A10000%2C%22timestamp%22%3A1527690950%2C%22to_user%22%3A%22wxid_zj2cahpwzgie12%22%2C%22uin%22%3A324216852%7D%5D%0A","msgId":"","userId":"padchattest"}
22:35:51 SILL PuppetPadchat WebSocket Server rawData result: {"content":"群主已恢复默认进群方式。","continue":1,"description":"","from_user":"6350854677@chatroom","msg_id":"4838179978529771707","msg_source":"","msg_type":5,"status":1,"sub_type":10000,"timestamp":1527690950,"to_user":"wxid_zj2cahpwzgie12","uin":324216852}
22:35:51 VERB Room ready()
22:35:51 SILL PuppetAccessory #13<Contact> get puppet()
22:35:51 SILL PuppetAccessory <Contact> static get puppet()
22:35:51 SILL Contact ready() @ PuppetPadchat<default>
22:35:51 SILL PuppetAccessory #13<Contact> get puppet()
22:35:51 SILL PuppetAccessory <Contact> static get puppet()
22:35:51 SILL Puppet contactPayload(群主已恢复默认进群方式。) @ PuppetPadchat<default>
22:35:51 VERB PuppetPadchat contactRawPayload(群主已恢复默认进群方式。)
22:35:51 SILL PuppetPadchatBridge sendToWebSocket: {"userId":"padchattest","msgId":"cjht7qy3s000qp6wdsw7uxnm8","apiName":"WXGetContact","param":["%E7%BE%A4%E4%B8%BB%E5%B7%B2%E6%81%A2%E5%A4%8D%E9%BB%98%E8%AE%A4%E8%BF%9B%E7%BE%A4%E6%96%B9%E5%BC%8F%E3%80%82"]}
22:35:51 SILL PuppetPadchat return apiName: WXGetContact, msgId: cjht7qy3s000qp6wdsw7uxnm8
22:35:51 WARN PuppetPadchatBridge WXGetContact cannot get user_name, id: 群主已恢复默认进群方式。
22:35:51 VERB PuppetPadchat contactRawPayloadParser([object Object])
22:35:51 ERR Contact ready() this.puppet.contactPayload(Contact) exception: cannot get user_name(wxid)!
22:35:51 ERR Config ###########################
22:35:51 ERR Config unhandledRejection: Error: cannot get user_name(wxid)! [object Promise]
22:35:51 ERR Config ###########################
22:35:51 ERR Config process.on(unhandledRejection) promise.catch(cannot get user_name(wxid)!)
Config Error: cannot get user_name(wxid)!
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:557:13)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:21:12)
    at PuppetPadchat.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:418:16)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:402:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:21642) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 15)
22:35:52 SILL PuppetPadchat WebSocket Server result: {"apiName":"","data":"%5B%7B%22continue%22%3A0%2C%22msg_type%22%3A32768%2C%22status%22%3A1%2C%22uin%22%3A324216852%7D%5D%0A","msgId":"","userId":"padchattest"}
22:35:52 SILL PuppetPadchat WebSocket Server rawData result: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
22:35:52 SILL PuppetPadchat WebSocket Server: get empty message msg_id form Tencent server
```

**Comment by zixia** [comment]
Should have been fixed today.

**Comment by lijiarui** [comment]
fix
