### ISSUE TITLE
当机器人是群主，其他人扫描机器人的二维码进入群的时候，会抛出异常

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#56]
```shell
19:07:42 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:07:42 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:08:02 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(ws.on(message))
19:08:02 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(#9 from debounceQueue)
19:08:02 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
19:08:02 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=#9 from debounceQueue})
19:08:02 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:08:03 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:08:04 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:08:13 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
19:08:13 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
19:08:13 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
19:08:13 VERB PuppetPadchat onPadchatMessage({id=3244658260828188781, type=Recalled(5)})
rawPayload: { content:
   '5616634434@chatroom:\n<sysmsg type="delchatroommember">\n\t<delchatroommember>\n\t\t<plain><![CDATA["李佳芮"通过扫描你分享的二维码加入群聊  ]]></plain>\n\t\t<text><![CDATA["李佳芮"通过扫描你分享的二维码加入群聊  ]]></text>\n\t\t<link>\n\t\t\t<scene>qrcode</scene>\n\t\t\t<text><![CDATA[  撤销]]></text>\n\t\t\t<memberlist>\n\t\t\t\t<username><![CDATA[qq512436430]]></username>\n\t\t\t</memberlist>\n\t\t\t<qrcode><![CDATA[http://weixin.qq.com/g/A7MgUgqtga7G9y03]]></qrcode>\n\t\t</link>\n\t</delchatroommember>\n</sysmsg>\n',
  continue: 1,
  description: '',
  from_user: '5616634434@chatroom',
  msg_id: '3244658260828188781',
  msg_source: '',
  msg_type: 5,
  status: 1,
  sub_type: 10002,
  timestamp: 1528830493,
  to_user: 'wxid_zj2cahpwzgie12',
  uin: 324216852 }
19:08:13 VERB Message static create(3244658260828188781)
19:08:13 SILL Accessory #39<Message> constructor()
19:08:13 VERB Message constructor(3244658260828188781) for class Message
19:08:13 VERB Message ready()
19:08:13 SILL Puppet messagePayloadCache(3244658260828188781) cache MISS
19:08:13 VERB Puppet messagePayload(id=3244658260828188781, noCache=false)
19:08:13 SILL Puppet messagePayloadCache(3244658260828188781) cache MISS
19:08:13 VERB PuppetPadChat messageRawPayloadParser({msg_id="3244658260828188781"})
19:08:13 SILL PuppetPadchat messagePayload({"id":"3244658260828188781","timestamp":1528830493,"text":"<sysmsg type=\"delchatroommember\">\n\t<delchatroommember>\n\t\t<plain><![CDATA[\"李佳芮\"通过扫描你分享的二维码加入群聊  ]]></plain>\n\t\t<text><![CDATA[\"李佳芮\"通过扫描你分享的二维码加入群聊  ]]></text>\n\t\t<link>\n\t\t\t<scene>qrcode</scene>\n\t\t\t<text><![CDATA[  撤销]]></text>\n\t\t\t<memberlist>\n\t\t\t\t<username><![CDATA[qq512436430]]></username>\n\t\t\t</memberlist>\n\t\t\t<qrcode><![CDATA[http://weixin.qq.com/g/A7MgUgqtga7G9y03]]></qrcode>\n\t\t</link>\n\t</delchatroommember>\n</sysmsg>\n","type":0,"fromId":"5616634434@chatroom","toId":"wxid_zj2cahpwzgie12","roomId":"5616634434@chatroom"})
19:08:13 SILL Puppet messagePayload(3244658260828188781) cache SET
19:08:13 SILL Contact ready() @ PuppetPadchat<default>
19:08:13 SILL Puppet contactPayload(5616634434@chatroom) cache MISS
19:08:13 SILL Puppet contactPayload(5616634434@chatroom) cache MISS
19:08:13 SILL PuppetPadchat contactRawPayload(5616634434@chatroom)
19:08:13 SILL PuppetPadchatBridge contactRawPayload(5616634434@chatroom)
19:08:13 SILL PuppetPadchatBridge contactRawPayload(5616634434@chatroom) retry() attempt=1
19:08:13 SILL Puppet contactPayload(5616634434@chatroom) cache MISS
19:08:13 ERR Contact ready() this.puppet.contactPayload(Contact) exception: should use WXGetRoomPayload because get a room id :5616634434@chatroom
19:08:13 ERR Config ###########################
19:08:13 ERR Config unhandledRejection: Error: should use WXGetRoomPayload because get a room id :5616634434@chatroom [object Promise]
19:08:13 ERR Config ###########################
19:08:13 ERR Config process.on(unhandledRejection) promise.catch(should use WXGetRoomPayload because get a room id :5616634434@chatroom)
Config Error: should use WXGetRoomPayload because get a room id :5616634434@chatroom
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:640:13)
    at Generator.next (<anonymous>)
    at /home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:3:12)
    at Bridge.WXGetContactPayload (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:536:16)
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:853:41)
    at Generator.next (<anonymous>)
    at /home/ubuntu/workspace/src/puppet-padchat/bridge.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:3:12)
    at misc_1.default.retry (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:841:66)
    at /home/ubuntu/workspace/node_modules/promise-retry/index.js:29:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5441) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 8)
19:08:14 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:08:14 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:08:34 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(ws.on(message))
19:08:34 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(#10 from debounceQueue)
19:08:34 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
19:08:34 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=#10 from debounceQueue})
19:08:54 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(#10 from debounceQueue)
19:08:54 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(#11 from debounceQueue)
19:08:54 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
19:08:54 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=#11 from debounceQueue})
19:09:14 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(#11 from debounceQueue)
```

**Comment by zixia** [comment]
Should have been fixed in the latest code base.

**Comment by lijiarui** [comment]
fixed
