### ISSUE TITLE
英文环境下，机器人拉3个人进群,机器人不是群主, 抛异常

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#57]
```shell
19:22:02 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:22:22 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(ws.on(message))
19:22:22 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(#43 from debounceQueue)
19:22:22 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
19:22:22 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=#43 from debounceQueue})
19:22:29 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:22:29 VERB PuppetPadchat onPadchatMessage({id=232220931339852872, type=Recalled(5)})
rawPayload: { content:
   '12740017638@chatroom:\n<sysmsg type="delchatroommember">\n\t<delchatroommember>\n\t\t<plain><![CDATA[You invited 卓桓、Zhuohuan, 太阁_传话助手, 桔小秘 to the group chat.   ]]></plain>\n\t\t<text><![CDATA[You invited 卓桓、Zhuohuan, 太阁_传话助手, 桔小秘 to the group chat.   ]]></text>\n\t\t<link>\n\t\t\t<scene>invite</scene>\n\t\t\t<text><![CDATA[  Revoke]]></text>\n\t\t\t<memberlist>\n\t\t\t\t<username><![CDATA[lizhuohuan]]></username>\n\t\t\t\t<username><![CDATA[wxid_lredtm37y7rc22]]></username>\n\t\t\t\t<username><![CDATA[wxid_seytcj5hxxsh12]]></username>\n\t\t\t</memberlist>\n\t\t</link>\n\t</delchatroommember>\n</sysmsg>\n',
  continue: 1,
  description: '',
  from_user: '12740017638@chatroom',
  msg_id: '232220931339852872',
  msg_source: '',
  msg_type: 5,
  status: 1,
  sub_type: 10002,
  timestamp: 1528831349,
  to_user: 'wxid_zj2cahpwzgie12',
  uin: 324216852 }
19:22:29 VERB Message static create(232220931339852872)
19:22:29 SILL Accessory #56<Message> constructor()
19:22:29 VERB Message constructor(232220931339852872) for class Message
19:22:29 VERB Message ready()
19:22:29 SILL Puppet messagePayloadCache(232220931339852872) cache MISS
19:22:29 VERB Puppet messagePayload(id=232220931339852872, noCache=false)
19:22:29 SILL Puppet messagePayloadCache(232220931339852872) cache MISS
19:22:29 VERB PuppetPadChat messageRawPayloadParser({msg_id="232220931339852872"})
19:22:29 SILL PuppetPadchat messagePayload({"id":"232220931339852872","timestamp":1528831349,"text":"<sysmsg type=\"delchatroommember\">\n\t<delchatroommember>\n\t\t<plain><![CDATA[You invited 卓桓、Zhuohuan, 太阁_传话助手, 桔小秘 to the group chat.   ]]></plain>\n\t\t<text><![CDATA[You invited 卓桓、Zhuohuan, 太阁_传话助手, 桔小秘 to the group chat.   ]]></text>\n\t\t<link>\n\t\t\t<scene>invite</scene>\n\t\t\t<text><![CDATA[  Revoke]]></text>\n\t\t\t<memberlist>\n\t\t\t\t<username><![CDATA[lizhuohuan]]></username>\n\t\t\t\t<username><![CDATA[wxid_lredtm37y7rc22]]></username>\n\t\t\t\t<username><![CDATA[wxid_seytcj5hxxsh12]]></username>\n\t\t\t</memberlist>\n\t\t</link>\n\t</delchatroommember>\n</sysmsg>\n","type":0,"fromId":"12740017638@chatroom","toId":"wxid_zj2cahpwzgie12","roomId":"12740017638@chatroom"})
19:22:29 SILL Puppet messagePayload(232220931339852872) cache SET
19:22:29 SILL Contact ready() @ PuppetPadchat<default>
19:22:29 SILL Puppet contactPayload(12740017638@chatroom) cache MISS
19:22:29 SILL Puppet contactPayload(12740017638@chatroom) cache MISS
19:22:29 SILL PuppetPadchat contactRawPayload(12740017638@chatroom)
19:22:29 SILL PuppetPadchatBridge contactRawPayload(12740017638@chatroom)
19:22:29 SILL PuppetPadchatBridge contactRawPayload(12740017638@chatroom) retry() attempt=1
19:22:29 SILL Puppet contactPayload(12740017638@chatroom) cache MISS
19:22:29 ERR Contact ready() this.puppet.contactPayload(Contact) exception: should use WXGetRoomPayload because get a room id :12740017638@chatroom
19:22:29 ERR Config ###########################
19:22:29 ERR Config unhandledRejection: Error: should use WXGetRoomPayload because get a room id :12740017638@chatroom [object Promise]
19:22:29 ERR Config ###########################
19:22:29 ERR Config process.on(unhandledRejection) promise.catch(should use WXGetRoomPayload because get a room id :12740017638@chatroom)
Config Error: should use WXGetRoomPayload because get a room id :12740017638@chatroom
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:640:13)
    at Generator.next (<anonymous>)
    at /home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:3:12)
    at Bridge.WXGetContactPayload (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:536:16)
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:853:41)
    at Generator.next (<anonymous>)
    at /home/ubuntu/workspace/src/puppet-padchat/bridge.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:3:12)
    at misc_1.default.retry (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:841:66)
    at /home/ubuntu/workspace/node_modules/promise-retry/index.js:29:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5441) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 12)
19:22:30 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
```

**Comment by lijiarui** [comment]
fixed
