### ISSUE TITLE
英文环境下，扫描二维码入群，扫描机器人分享的二维码入群,机器人是群主，抛出异常

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#58]
```shell
19:30:05 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:30:10 VERB PuppetPadchat onPadchatMessage({id=4650182269246977858, type=Recalled(5)})
rawPayload: { content:
   '6350854677@chatroom:\n<sysmsg type="delchatroommember">\n\t<delchatroommember>\n\t\t<plain><![CDATA["李佳芮" joined group chat via the QR code you shared.  ]]></plain>\n\t\t<text><![CDATA["李佳芮" joined group chat via the QR code you shared.  ]]></text>\n\t\t<link>\n\t\t\t<scene>qrcode</scene>\n\t\t\t<text><![CDATA[  Revoke]]></text>\n\t\t\t<memberlist>\n\t\t\t\t<username><![CDATA[qq512436430]]></username>\n\t\t\t</memberlist>\n\t\t\t<qrcode><![CDATA[http://weixin.qq.com/g/Ay3k_6_NZRM-0eGu]]></qrcode>\n\t\t</link>\n\t</delchatroommember>\n</sysmsg>\n',
  continue: 1,
  description: '',
  from_user: '6350854677@chatroom',
  msg_id: '4650182269246977858',
  msg_source: '',
  msg_type: 5,
  status: 1,
  sub_type: 10002,
  timestamp: 1528831810,
  to_user: 'wxid_zj2cahpwzgie12',
  uin: 324216852 }
19:30:10 VERB Message static create(4650182269246977858)
19:30:10 SILL Accessory #70<Message> constructor()
19:30:10 VERB Message constructor(4650182269246977858) for class Message
19:30:10 VERB Message ready()
19:30:10 SILL Puppet messagePayloadCache(4650182269246977858) cache MISS
19:30:10 VERB Puppet messagePayload(id=4650182269246977858, noCache=false)
19:30:10 SILL Puppet messagePayloadCache(4650182269246977858) cache MISS
19:30:10 VERB PuppetPadChat messageRawPayloadParser({msg_id="4650182269246977858"})
19:30:10 SILL PuppetPadchat messagePayload({"id":"4650182269246977858","timestamp":1528831810,"text":"<sysmsg type=\"delchatroommember\">\n\t<delchatroommember>\n\t\t<plain><![CDATA[\"李佳芮\" joined group chat via the QR code you shared.  ]]></plain>\n\t\t<text><![CDATA[\"李佳芮\" joined group chat via the QR code you shared.  ]]></text>\n\t\t<link>\n\t\t\t<scene>qrcode</scene>\n\t\t\t<text><![CDATA[  Revoke]]></text>\n\t\t\t<memberlist>\n\t\t\t\t<username><![CDATA[qq512436430]]></username>\n\t\t\t</memberlist>\n\t\t\t<qrcode><![CDATA[http://weixin.qq.com/g/Ay3k_6_NZRM-0eGu]]></qrcode>\n\t\t</link>\n\t</delchatroommember>\n</sysmsg>\n","type":0,"fromId":"6350854677@chatroom","toId":"wxid_zj2cahpwzgie12","roomId":"6350854677@chatroom"})
19:30:10 SILL Puppet messagePayload(4650182269246977858) cache SET
19:30:10 SILL Contact ready() @ PuppetPadchat<default>
19:30:10 SILL Puppet contactPayload(6350854677@chatroom) cache MISS
19:30:10 SILL Puppet contactPayload(6350854677@chatroom) cache MISS
19:30:10 SILL PuppetPadchat contactRawPayload(6350854677@chatroom)
19:30:10 SILL PuppetPadchatBridge contactRawPayload(6350854677@chatroom)
19:30:10 SILL PuppetPadchatBridge contactRawPayload(6350854677@chatroom) retry() attempt=1
19:30:10 SILL Puppet contactPayload(6350854677@chatroom) cache MISS
19:30:10 ERR Contact ready() this.puppet.contactPayload(Contact) exception: should use WXGetRoomPayload because get a room id :6350854677@chatroom
19:30:10 ERR Config ###########################
19:30:10 ERR Config unhandledRejection: Error: should use WXGetRoomPayload because get a room id :6350854677@chatroom [object Promise]
19:30:10 ERR Config ###########################
19:30:10 ERR Config process.on(unhandledRejection) promise.catch(should use WXGetRoomPayload because get a room id :6350854677@chatroom)
Config Error: should use WXGetRoomPayload because get a room id :6350854677@chatroom
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:640:13)
    at Generator.next (<anonymous>)
    at /home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:3:12)
    at Bridge.WXGetContactPayload (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:536:16)
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:853:41)
    at Generator.next (<anonymous>)
    at /home/ubuntu/workspace/src/puppet-padchat/bridge.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:3:12)
    at misc_1.default.retry (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:841:66)
    at /home/ubuntu/workspace/node_modules/promise-retry/index.js:29:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5441) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 22)
19:30:11 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:30:11 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
19:30:32 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(ws.on(message))
19:30:32 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(#59 from debounceQueue)
19:30:32 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
19:30:32 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=#59 from debounceQueue})
19:30:52 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(#59 from debounceQueue)
19:30:52 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(#60 from debounceQueue)
19:30:52 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
19:30:52 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=#60 from debounceQueue})
19:31:12 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(#60 from debounceQueue)
```

**Comment by lijiarui** [comment]
fixed
