### ISSUE TITLE
When I sync my contact I get the folllowing error

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#73]
Run `conatct-bot.ts`

@zixia may need your help..

```shell
00:23:58 WARN PadchatRpc WXGetContact cannot get user_name, id: lizhuohuan, "{}"
00:23:58 ERR Contact ready() this.puppet.contactPayload(Contact) exception: cannot get user_name from raw payload: {}
(node:74322) UnhandledPromiseRejectionWarning: Error: cannot get user_name from raw payload: {}
    at Object.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/pure-function-helpers/contact-raw-payload-parser.ts:42:11)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:700:37)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:21:12)
    at PuppetPadchat.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:522:16)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:494:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:74322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
{}
00:23:59 WARN PadchatRpc WXGetContact cannot get user_name, id: lizhuohuan, "{}"
00:23:59 ERR Contact ready() this.puppet.contactPayload(Contact) exception: cannot get user_name from raw payload: {}
(node:74322) UnhandledPromiseRejectionWarning: Error: cannot get user_name from raw payload: {}
    at Object.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/pure-function-helpers/contact-raw-payload-parser.ts:42:11)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:700:37)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:21:12)
    at PuppetPadchat.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:522:16)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:494:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:74322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 56)
{}
00:23:59 WARN PadchatRpc WXGetContact cannot get user_name, id: lizhuohuan, "{}"
00:23:59 ERR Contact ready() this.puppet.contactPayload(Contact) exception: cannot get user_name from raw payload: {}
(node:74322) UnhandledPromiseRejectionWarning: Error: cannot get user_name from raw payload: {}
    at Object.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/pure-function-helpers/contact-raw-payload-parser.ts:42:11)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:700:37)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:21:12)
    at PuppetPadchat.contactRawPayloadParser (/Users/jiaruili/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:522:16)
    at PuppetPadchat.<anonymous> (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:494:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/src/puppet/puppet.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:74322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 58)
```

**Comment by zixia** [comment]
Excuse me, who need whose help?

**Comment by lijiarui** [comment]
fix in https://github.com/Chatie/wechaty/pull/1389
