### ISSUE TITLE
WXGetChatRoomMember throw error `no encodedText`

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#76]
see more : https://github.com/Chatie/wechaty/issues/1365

When sync Room and call `WXGetChatRoomMember()` 
```
10:40:54 SILL PadchatRpc onServerMessagePadchat() discard empty payload.data for apiName: WXGetChatRoomMember
10:40:54 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
10:40:54 SILL PuppetPadchat startWatchdog() padchatManager.on(heartbeat)
10:40:54 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
10:40:54 SILL PadchatRpc WXGetChatRoomMember() result: {}
Error: no encodedText
    at Object.padchatDecode (/wechaty/src/puppet-padchat/pure-function-helpers/padchat-decode.ts:4:11)
    at PadchatManager.<anonymous> (/wechaty/src/puppet-padchat/padchat-rpc.ts:739:64)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-padchat/padchat-rpc.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
decode error data:  undefined
10:40:54 WARN PadchatRpc WXGetChatRoomMember(6293981429@chatroom) result.member decode error: Error: no encodedText
10:40:54 VERB PuppetPadchatManager roomMemberRawPayloadDirty(6293981429)
10:40:54 VERB PuppetPadchatManager roomRawPayloadDirty(6293981429)
10:40:54 VERB PuppetPadchatManager getRoomMemberIdList(6293981429) length=0
10:40:54 SILL PuppetPadchat roomMemberList()=0
10:41:01 SILL PadchatRpc onServerMessagePadchat() discard empty payload.data for apiName: WXGetChatRoomMember
10:41:01 SILL PadchatRpc WXGetChatRoomMember() result: {}
Error: no encodedText
    at Object.padchatDecode (/wechaty/src/puppet-padchat/pure-function-helpers/padchat-decode.ts:4:11)
    at PadchatManager.<anonymous> (/wechaty/src/puppet-padchat/padchat-rpc.ts:739:64)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-padchat/padchat-rpc.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
decode error data:  undefined
```

related code in `padchat-rpc.ts` as follows, maybe it means we get result from server is {}

**maybe should change as follows? Not sure...**

```diff
  /**
   * Get all member of a room by room id
   * @param {any} roomId        chatroom_id
   */
  public async WXGetChatRoomMember(roomId: string): Promise<null | PadchatRoomMemberListPayload> {
    const result = await this.rpcCall('WXGetChatRoomMember', roomId)
-     if (!result) {
+    if (!result || result === {}) {
      throw Error('PadchatRpc, WXGetChatRoomMember, cannot get result from websocket server!')
    }

    // roomId not exist. (or no permision?)
    // See: https://github.com/lijiarui/wechaty-puppet-padchat/issues/64#issuecomment-397319016
    if (result.status === -19) {
      return null
    }

    /**
     * Bot quit the room, no roomId
     * See: https://github.com/lijiarui/wechaty-puppet-padchat/issues/38
     * {"chatroom_id":0,"count":0,"member":"null\n","message":"","status":0,"user_name":""}
     */
   if (result.count === 0 && result.status === 0 && result.chatroom_id === 0) {
      return null
    }

    log.silly('PadchatRpc', 'WXGetChatRoomMember() result: %s', JSON.stringify(result).substr(0, 500))

    // 00:40:44 SILL PadchatRpc WXGetChatRoomMember() result: {"chatroom_id":0,"count":0,"member":"null\n","message":"","status":0,"user_name":""}

    try {
      const tryMemberList: null | PadchatRoomMemberPayload[] = padchatDecode(result.member)

      if (Array.isArray(tryMemberList)) {
        result.member = tryMemberList
      } else if (tryMemberList !== null) {
        log.warn('PadchatRpc', 'WXGetChatRoomMember(%s) member is neither array nor null: %s', roomId, JSON.stringify(result.member))
        // throw Error('faild to parse chatroom member!')
        result.member = []
      }

    } catch (e) {
      console.error(e)
      console.error('decode error data: ', result.member)
      log.warn('PadchatRpc', 'WXGetChatRoomMember(%s) result.member decode error: %s', roomId, e)
      result.member = []
    }
    return result
  }
```

**Comment by lijiarui** [comment]
@windmemory Is this issue fixed yet?

**Comment by windmemory** [comment]
I have no idea, is this issue still happening?

**Comment by windmemory** [comment]
There is another issue has been closed: https://github.com/lijiarui/wechaty-puppet-padchat/issues/66

Seems like this is an old issue, and got fixed with some refactors. 

Please double check the issue, if not happened again, please close it.

**Comment by lijiarui** [comment]
This may fix by the recent update.
