### ISSUE TITLE
Can't starrt

### ISSUE THREAD

**Issue by newip** [lijiarui/wechaty-puppet-padchat#82]
MacOS, native installation

```
RobinH:wechaty-getting-started robinhe$ npm install
audited 915 packages in 5.166s
found 0 vulnerabilities
```

```
RobinH:wechaty-getting-started robinhe$ npm start

> wechaty-getting-started@1.0.0 start /Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started
> ts-node examples/starter-bot.js

08:31:11 INFO Wechaty start() v0.17.98 is starting...
08:31:11 ERR Accessory static get puppet() please see issue #1217: https://github.com/Chatie/wechaty/issues/1217
08:31:11 INFO Wechaty initPuppet() using puppet: puppeteer
08:31:11 ERR PuppetPuppeteerBridge init() exception: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
08:31:11 ERR PuppetPuppeteer initBridge() exception: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
Error: no page
    at Bridge.<anonymous> (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/src/bridge.ts:303:13)
    at Generator.next (<anonymous>)
    at /Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:26:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:22:12)
    at Bridge.quit (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:246:16)
    at PuppetPuppeteer.<anonymous> (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:332:25)
    at Generator.throw (<anonymous>)
    at rejected (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at <anonymous>
08:31:11 ERR PuppetPuppeteer start() exception: Error: Error: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
Error: Error: Error: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at PuppetPuppeteer.puppet.on.error (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:586:32)
    at PuppetPuppeteer.emit (events.js:159:13)
    at PuppetPuppeteer.emit (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet/src/puppet.ts:246:18)
    at PuppetPuppeteer.<anonymous> (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:177:12)
    at Generator.throw (<anonymous>)
    at rejected (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at <anonymous>
08:31:11 ERR Wechaty start() exception: Error: Error: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
Error: Error: Error: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at PuppetPuppeteer.puppet.on.error (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:586:32)
    at PuppetPuppeteer.emit (events.js:159:13)
    at PuppetPuppeteer.emit (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet/src/puppet.ts:246:18)
    at PuppetPuppeteer.<anonymous> (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:177:12)
    at Generator.throw (<anonymous>)
    at rejected (/Users/robinhe/Documents/Dev/GitHub/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at <anonymous>
```

**Comment by zixia** [comment]
Sorry, the master branch of this repo is broken from yesterday. 

Please wait for the fix before you try again, I'll let you know it by keep posting the progress at here.

**Comment by zixia** [comment]
Oh, I saw that you are using Puppeteer.

If you are not testing with padchat, please use Wechaty v0.14 instead. 

Because currently the versions above v0.14 is all UNSTABLE and for Alpha/Beta test only.

**Comment by newip** [comment]
started after set the env to change it to padchat.

WECHATY_PUPPET_PADCHAT_TOKEN=botorange_tempory_token WECHATY_PUPPET=padchat node ./starter-bot.js

**Comment by zixia** [comment]
Glad to hear that, Cheers!
